// Package mux runs agents inside a private tmux server (socket "optimus") so
// they keep running when the optimus UI exits, and can be attached, watched,
// fed prompts and killed from one place.
package mux

import (
	"bytes"
	"crypto/rand"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/Unchained-Labs/optimus/internal/config"
)

// Socket is the tmux server name; OPTIMUS_SOCKET selects another server
// (e.g. to keep a demo or test apart from your real agents).
var Socket = socketName()

const Session = "optimus"

func socketName() string {
	if s := os.Getenv("OPTIMUS_SOCKET"); s != "" {
		return s
	}
	return "optimus"
}

// Window is one agent pane managed by optimus.
type Window struct {
	ID        string // tmux window id, e.g. @3
	Pane      string // tmux pane id, e.g. %5 (agents run in a single pane)
	Index     int
	Name      string
	Agent     string
	Cwd       string
	SessionID string // agent session id when known
	Command   string // current foreground command
	PID       int
	Dead      bool
	Activity  time.Time
	Created   time.Time
	// set when the agent works in its own git worktree
	Worktree string
	Repo     string
	Base     string
	Branch   string
	// State is the last state the notifier recorded (@optimus_state)
	State string
}

func Available() bool {
	_, err := exec.LookPath("tmux")
	return err == nil
}

func tmux(args ...string) *exec.Cmd {
	cmd := exec.Command("tmux", append([]string{"-L", Socket, "-f", confPath()}, args...)...)
	cmd.Env = envWithoutTMUX()
	return cmd
}

func run(args ...string) (string, error) {
	var out, errb bytes.Buffer
	cmd := tmux(args...)
	cmd.Stdout, cmd.Stderr = &out, &errb
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(errb.String())
		if msg == "" {
			msg = err.Error()
		}
		return out.String(), errors.New("tmux: " + msg)
	}
	return out.String(), nil
}

func envWithoutTMUX() []string {
	var env []string
	for _, e := range os.Environ() {
		if !strings.HasPrefix(e, "TMUX=") && !strings.HasPrefix(e, "TMUX_PANE=") {
			env = append(env, e)
		}
	}
	return env
}

func confPath() string { return filepath.Join(config.Dir(), "tmux.conf") }

// confText is loaded when the optimus tmux server starts. Alt-q (or prefix d)
// detaches back to the optimus UI; Alt-n jumps to the next agent that needs
// you.
func confText() string {
	self, err := os.Executable()
	if err != nil {
		self = "optimus"
	}
	return `# generated by optimus — edits are overwritten
set -g mouse on
set -g history-limit 50000
set -g escape-time 10
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
# options newer than some distro tmux builds: -q ignores them where unknown
set -gq allow-passthrough on
set -gq extended-keys on
set -g base-index 1
set -g renumber-windows on
set -g display-time 4000
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-left "#[bg=#f38ba8,fg=#1e1e2e,bold] OPTIMUS #[default] "
set -g status-left-length 20
set -g status-interval 15
set -g status-right "#[fg=#a6adc8]#(` + shellQuote(self) + ` fleet --tmux)  #[fg=#f9e2af]Alt-n#[fg=#a6adc8] next ◆  #[fg=#f9e2af]Alt-q#[fg=#a6adc8] back "
set -g status-right-length 110
set -g window-status-format " #I #W#{?#{==:#{@optimus_state},input}, #[fg=#f38ba8]◆,} "
set -g window-status-current-format "#[bg=#89b4fa,fg=#1e1e2e,bold] #I #W "
set -g message-style "bg=#f9e2af,fg=#1e1e2e,bold"
set -g pane-border-style "fg=#45475a"
set -g pane-active-border-style "fg=#89b4fa"
bind -n M-q detach-client
bind -n M-Left previous-window
bind -n M-Right next-window
bind -n M-n run-shell -b "` + shellQuote(self) + ` next --switch"
`
}

// shellQuote quotes s for a POSIX shell.
func shellQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// ensureConf writes the config and, when the server is already running with
// an older one, reloads it so new bindings apply without a restart.
func ensureConf() error {
	if err := os.MkdirAll(config.Dir(), 0o755); err != nil {
		return err
	}
	want := confText()
	cur, _ := os.ReadFile(confPath())
	if string(cur) == want {
		return nil
	}
	if err := os.WriteFile(confPath(), []byte(want), 0o644); err != nil {
		return err
	}
	if Running() {
		_, _ = run("source-file", confPath())
	}
	return nil
}

func Running() bool {
	_, err := run("has-session", "-t", "="+Session)
	return err == nil
}

// Spawn starts a new window running argv in dir and tags it with optimus
// metadata. It starts the server and session on first use.
func Spawn(name, agent, dir, sessionID string, argv []string) (string, error) {
	if !Available() {
		return "", errors.New("tmux is not installed")
	}
	if err := ensureConf(); err != nil {
		return "", err
	}
	if dir == "" {
		dir, _ = os.Getwd()
	}
	if st, err := os.Stat(dir); err != nil || !st.IsDir() {
		return "", fmt.Errorf("directory %q does not exist", dir)
	}
	name = sanitize(name)
	format := "#{window_id}"
	var args []string
	if Running() {
		args = []string{"new-window", "-d", "-P", "-F", format, "-t", Session + ":", "-n", name, "-c", dir}
	} else {
		args = []string{"new-session", "-d", "-P", "-F", format, "-s", Session, "-n", name, "-c", dir, "-x", "220", "-y", "50"}
	}
	args = append(args, "--")
	args = append(args, argv...)
	out, err := run(args...)
	if err != nil {
		return "", err
	}
	id := strings.TrimSpace(out)
	for k, v := range map[string]string{"@optimus_agent": agent, "@optimus_cwd": dir, "@optimus_session": sessionID, "@optimus_created": strconv.FormatInt(time.Now().Unix(), 10)} {
		if v != "" {
			_, _ = run("set-option", "-w", "-t", id, k, v)
		}
	}
	// keep the name we chose instead of tmux renaming it after the process
	_, _ = run("set-option", "-w", "-t", id, "automatic-rename", "off")
	return id, nil
}

var unsafe = regexp.MustCompile(`[^A-Za-z0-9._+-]+`)

// Sanitize makes s usable as a window name.
func Sanitize(s string) string { return sanitize(s) }

func sanitize(s string) string {
	s = strings.Trim(unsafe.ReplaceAllString(s, "-"), "-")
	if len(s) > 32 {
		s = s[:32]
	}
	if s == "" {
		s = "agent"
	}
	return s
}

// fieldSep separates fields in tmux format output. It must be printable:
// tmux 3.3+ escapes control characters (a \x1f comes back as the text "\037").
const fieldSep = "|~|"

// List returns every optimus window.
func List() ([]Window, error) {
	if !Available() || !Running() {
		return nil, nil
	}
	f := strings.Join([]string{"#{window_id}", "#{window_index}", "#{window_name}", "#{@optimus_agent}", "#{@optimus_cwd}", "#{@optimus_session}", "#{pane_current_command}", "#{pane_pid}", "#{pane_dead}", "#{window_activity}", "#{@optimus_created}", "#{pane_current_path}", "#{pane_id}", "#{@optimus_worktree}", "#{@optimus_repo}", "#{@optimus_base}", "#{@optimus_branch}", "#{@optimus_state}"}, fieldSep)
	out, err := run("list-windows", "-t", "="+Session, "-F", f)
	if err != nil {
		return nil, err
	}
	var ws []Window
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		p := strings.Split(line, fieldSep)
		if len(p) < 18 {
			continue
		}
		w := Window{ID: p[0], Name: p[2], Agent: p[3], Cwd: p[4], SessionID: p[5], Command: p[6], Dead: p[8] == "1"}
		w.Index, _ = strconv.Atoi(p[1])
		w.PID, _ = strconv.Atoi(p[7])
		if a, err := strconv.ParseInt(p[9], 10, 64); err == nil {
			w.Activity = time.Unix(a, 0)
		}
		if c, err := strconv.ParseInt(p[10], 10, 64); err == nil {
			w.Created = time.Unix(c, 0)
		}
		if w.Cwd == "" {
			w.Cwd = p[11]
		}
		w.Pane = p[12]
		w.Worktree, w.Repo, w.Base, w.Branch, w.State = p[13], p[14], p[15], p[16], p[17]
		if w.Agent == "" {
			w.Agent = w.Command
		}
		ws = append(ws, w)
	}
	return ws, nil
}

// Resolve finds a window by id (@3), index (3), or name.
func Resolve(q string) (Window, error) {
	ws, err := List()
	if err != nil {
		return Window{}, err
	}
	for _, w := range ws {
		if w.ID == q || strconv.Itoa(w.Index) == q || w.Name == q {
			return w, nil
		}
	}
	return Window{}, fmt.Errorf("no optimus window %q", q)
}

// Capture returns the last n lines of a window's visible pane.
func Capture(id string, lines int) (string, error) {
	out, err := run("capture-pane", "-p", "-t", id, "-S", "-"+strconv.Itoa(lines))
	ls := strings.Split(out, "\n")
	for i, l := range ls {
		ls[i] = strings.TrimRight(l, " ")
	}
	return strings.TrimRight(strings.Join(ls, "\n"), "\n"), err
}

// Send pastes text into a window (bracketed paste, so multi-line prompts stay
// one message) and presses Enter when submit is set.
func Send(id, text string, submit bool) error {
	cmd := tmux("load-buffer", "-b", "optimus-send", "-")
	cmd.Stdin = strings.NewReader(text)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("tmux: %s", strings.TrimSpace(string(out)))
	}
	if _, err := run("paste-buffer", "-d", "-p", "-b", "optimus-send", "-t", id); err != nil {
		return err
	}
	if submit {
		// give the TUI a moment to process the paste before submitting
		time.Sleep(300 * time.Millisecond)
		_, err := run("send-keys", "-t", id, "Enter")
		return err
	}
	return nil
}

// Select makes a window the current one of the agents' session, so attached
// clients see it.
func Select(id string) error {
	_, err := run("select-window", "-t", id)
	return err
}

// Current is the current window of the agents' session.
func Current() (string, error) {
	out, err := run("display-message", "-p", "-t", Session+":", "#{window_id}")
	return strings.TrimSpace(out), err
}

// Message shows text in the status line of every client attached to the
// optimus server (a no-op when none is attached).
func Message(text string) {
	if !Available() || !Running() {
		return
	}
	out, err := run("list-clients", "-F", "#{client_name}")
	if err != nil {
		return
	}
	for _, c := range strings.Fields(out) {
		_, _ = run("display-message", "-c", c, text)
	}
}

// SetWindowOption tags a window (e.g. @optimus_state for the status bar).
func SetWindowOption(id, key, value string) {
	_, _ = run("set-option", "-w", "-t", id, key, value)
}

func Kill(id string) error {
	_, err := run("kill-window", "-t", id)
	return err
}

func Rename(id, name string) error {
	_, err := run("rename-window", "-t", id, sanitize(name))
	return err
}

// AttachCmd returns a command that attaches the terminal to a window. The
// caller runs it in the foreground; it returns when the user detaches.
func AttachCmd(id string) *exec.Cmd {
	if UsePopup() {
		return PopupCmd(id)
	}
	_, _ = run("select-window", "-t", id)
	cmd := tmux("attach-session", "-t", "="+Session)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	return cmd
}

// allowedKeys are the tmux key names remote clients may send (for phone-friendly
// buttons: answering prompts, interrupting, navigating menus).
var allowedKeys = map[string]bool{
	"Enter": true, "Escape": true, "Tab": true, "BTab": true, "Up": true, "Down": true, "Left": true, "Right": true,
	"C-c": true, "C-d": true, "C-l": true, "C-r": true, "C-o": true, "C-t": true, "Space": true, "BSpace": true,
	"PageUp": true, "PageDown": true, "y": true, "n": true, "1": true, "2": true, "3": true,
}

// Keys sends named keys (see allowedKeys) to a window.
func Keys(id string, keys ...string) error {
	for _, k := range keys {
		if !allowedKeys[k] {
			return fmt.Errorf("key %q not allowed", k)
		}
	}
	_, err := run(append([]string{"send-keys", "-t", id}, keys...)...)
	return err
}

// ViewCmd prepares a private view of one window for a remote terminal: a
// session grouped with the agents' session (so it shares the windows but has
// its own current window), without a status bar, removed by the returned
// cleanup func. The returned command attaches to it.
func ViewCmd(windowID string) (*exec.Cmd, func(), error) {
	var b [6]byte
	_, _ = rand.Read(b[:])
	view := fmt.Sprintf("view-%x", b)
	if _, err := run("new-session", "-d", "-s", view, "-t", "="+Session); err != nil {
		return nil, nil, err
	}
	// view names are random and unique, so plain targets are exact (tmux 3.2
	// does not accept the "=" exact-match prefix everywhere)
	cleanup := func() { _, _ = run("kill-session", "-t", view) }
	if _, err := run("set-option", "-t", view, "status", "off"); err != nil {
		cleanup()
		return nil, nil, err
	}
	if _, err := run("select-window", "-t", view+":"+windowID); err != nil {
		cleanup()
		return nil, nil, err
	}
	cmd := tmux("attach-session", "-t", view)
	cmd.Env = append(cmd.Env, "TERM=xterm-256color")
	return cmd, cleanup, nil
}

// SweepViews removes view sessions left behind by a crashed dashboard.
func SweepViews() {
	if !Running() {
		return
	}
	out, err := run("list-sessions", "-F", "#{session_name} #{session_attached}")
	if err != nil {
		return
	}
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		f := strings.Fields(line)
		if len(f) == 2 && strings.HasPrefix(f[0], "view-") && f[1] == "0" {
			_, _ = run("kill-session", "-t", f[0])
		}
	}
}

// ServiceSession holds optimus's own background processes (the web
// dashboard); it lives on the same tmux server but is never listed as an agent.
const ServiceSession = "optimus-svc"

// StartService (re)starts a named background process in the service session.
func StartService(name, dir string, argv []string) error {
	if err := ensureConf(); err != nil {
		return err
	}
	_, _ = run("kill-window", "-t", ServiceSession+":"+name)
	var args []string
	if _, err := run("has-session", "-t", "="+ServiceSession); err == nil {
		args = []string{"new-window", "-d", "-t", ServiceSession + ":", "-n", name, "-c", dir}
	} else {
		args = []string{"new-session", "-d", "-s", ServiceSession, "-n", name, "-c", dir}
	}
	_, err := run(append(append(args, "--"), argv...)...)
	return err
}

func StopService(name string) error {
	_, err := run("kill-window", "-t", ServiceSession+":"+name)
	return err
}

// AttachCmdQuiet is AttachCmd for use from the dashboard: it erases the
// "[detached (from session …)]" line tmux prints, so it doesn't pile up in the
// terminal once the dashboard exits.
func AttachCmdQuiet(id string) *exec.Cmd {
	if UsePopup() {
		return PopupCmd(id) // no "[detached]" line to clean up
	}
	base := AttachCmd(id)
	cmd := exec.Command("sh", append([]string{"-c", `"$@"; s=$?; printf '\033[1A\033[2K'; exit $s`, "sh"}, base.Args...)...)
	cmd.Env = base.Env
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	return cmd
}

// State guesses what an agent is doing from its screen.
type State string

const (
	StateBusy    State = "busy"
	StateWaiting State = "input"
	StateIdle    State = "idle"
	StateExited  State = "exited"
)

var (
	busyRe = regexp.MustCompile(`(?i)(esc to interrupt|ctrl\+c to interrupt|working\.\.\.|thinking…|running…)`)
	// prompts that wait for an answer: permission and approval dialogs,
	// Claude's workspace-trust check, y/n questions, numbered choices
	waitingRe = regexp.MustCompile(`(?i)(do you want to (proceed|make|create|run|allow|apply|edit)|allow command\?|would you like to run|[❯›] 1\. yes|allow once|\(y/n\)|\[y/n\]|waiting for (your )?(input|approval)|enter to confirm|trust this folder|one you trust\?)`)
)

func Detect(w Window, screen string) State {
	if w.Dead {
		return StateExited
	}
	// only the bottom of the screen reflects current state
	lines := strings.Split(strings.TrimRight(screen, "\n "), "\n")
	if len(lines) > 12 {
		lines = lines[len(lines)-12:]
	}
	tail := strings.Join(lines, "\n")
	switch {
	case waitingRe.MatchString(tail):
		return StateWaiting
	case busyRe.MatchString(tail):
		return StateBusy
	}
	return StateIdle
}
